version: '3.8'

services:
  api:
    build: ./
    #command: >
    #  sh -c "python manage.py flush --no-input &&
    #        python manage.py migrate &&
    #        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
      - static:/src/app/static
      - static:/src/app/media
           
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  
  db:
    container_name: database
    image: postgres:12.0-alpine
    env_file: ./.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
  static:
  media:
